---
title: "viz_and_eda_exploratory"
author: "Stephen Lewandowski"
date: "October 4, 2018"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)


  library(tidyverse)
  library(ggridges)
  library(patchwork)   # devtools::install_github("thomasp85/patchwork")
  library(rnoaa)

theme_set(theme_bw() + theme(legend.position = "bottom"))
```

## Viz and EDA -- Exploratory

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2016-01-01",
                      date_max = "2016-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) %>%
  select(name, id, date, month, everything())
```


Count first...
```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(number = n())

weather_df %>% 
  count(name, month)
```

## Grouped summaries

```{r}
weather_df %>%
  group_by(name, month) %>%
  summarize(number = n(),
            num_na = sum(is.na(tmax)),
            mean_tmax = mean(tmax),
            mean_prec = mean(prcp, na.rm = TRUE),
            median_prec = median(prcp, na.rm = TRUE),
            median_tmax = median(tmax),
            sd_tmax = sd(tmax))
```

